language: python

python:
  - "2.7"
  
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libspatialite5
    - sudo apt-get purge -y libgdal1h
    #- sudo apt-get install -y osmctools
    - sudo apt-get install -y python-software-properties
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y  
    - sudo apt-get update -q
    - sudo apt-get install gdal-devel
    - sudo apt-get install -y gdal-bin libgdal-dev
    - export CPLUS_INCLUDE_PATH=/usr/include/gdal
    - export C_INCLUDE_PATH=/usr/include/gdal
  
before_script:
    - createuser hot --superuser --createdb -U postgres
    
  
# command to install dependencies

install: "pip install -r requirements-dev.txt"

# command to run tests
script: ./manage.py test


  