notifications:
  email: false
  
language: python

python:
  - "2.7"
  
addons:
  postgresql: "9.3"
  
before_install:
    - sudo apt-get install -y libspatialite5 libspatialite-dev
    - sudo apt-get install -y python-software-properties
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
    - sudo apt-get update -qq
    - sudo apt-get install postgresql-9.3 postgresql-client-9.3 postgresql-contrib-9.3 postgresql-9.3-postgis-2.1
    - sudo apt-get install -y gdal-bin libgdal-dev
    - export CPLUS_INCLUDE_PATH=/usr/include/gdal
    - export C_INCLUDE_PATH=/usr/include/gdal
  
before_script:
    - psql -U postgres -c "create extension postgis"
    - createuser hot --superuser --createdb -U postgres

install:
    "pip install -r requirements-dev.txt"

# command to run tests
script:
    ./manage.py test


  