version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0-stretch
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            set -x
            sudo apt-get install libgdal-dev osmctools gdal-bin libspatialindex-dev
            virtualenv ./venv
            source venv/bin/activate
            export CPLUS_INCLUDE_PATH=/usr/include/gdal
            export C_INCLUDE_PATH=/usr/include/gdal
            pip install -r requirements-dev.txt
            make test
